- name: Airflow | Copy connections config file (>= 2.0)
  template:
    src: "airflow_connections.json.j2"
    dest: "{{ airflow_conf_path }}/airflow_connections.json"
    owner: "{{ airflow_user }}"
    group: "{{ airflow_group }}"
    mode: 0640
  when: airflow_version is version( '2.0.0', '>=')
  tags: 
    - connections
    - airflow_connections


- name: Airflow | Import Connections Config (> 2.0)
  become: true
  become_user: "{{ airflow_user }}"
  command:
    argv:
      - "{{ airflow_executable }}"
      - connections
      - import
      - "{{ airflow_conf_path }}/airflow_connections.json"
  when:
    - airflow_version is version( '2.0.0', '>=')
    - airflow_connections != None
  tags: 
    - connections
    - airflow_connections
